name: Build

on: [push]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v2.3.2
      - uses: mstksg/setup-stack@v2
      - run: |
          git clone https://github.com/diku-dk/futhark.git
          cd futhark
          stack setup
          stack build
          stack install
      - uses: goto-bus-stop/setup-zig@v1.2.3
        with:
          version: master
      - run: zig build
