name: Main

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2.3.2
      - name: Install ocl-icd
        run: |
          sudo apt update
          sudo apt install -y ocl-icd-opencl-dev
      - name: Install Futhark
        run: |
          wget https://futhark-lang.org/releases/futhark-nightly-linux-x86_64.tar.xz
          tar xvf futhark-nightly-linux-x86_64.tar.xz
          echo "::add-path::${PWD}/futhark-nightly-linux-x86_64/bin"
      - name: Setup Zig
        uses: goto-bus-stop/setup-zig@v1.2.3
        with:
          version: master
      - name: Build Calculo
        run: zig build
      - name: Archive artifacts
        uses: actions/upload-artifact@v2
        with:
          name: calculo
          path: |
            zig-cache/bin/calculo
  build-mac:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2.3.2
      - name: Install Futhark
        run: |
          brew install futhark
      - name: Setup Zig
        uses: goto-bus-stop/setup-zig@v1.2.3
        with:
          version: master
      - name: Build Calculo
        run: zig build
      - name: Archive artifacts
        uses: actions/upload-artifact@v2
        with:
          name: calculo
          path: |
            zig-cache/bin/calculo
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2.3.2
      - name: Install Futhark
        shell: powershell
        run: |
          Import-Module BitsTransfer
          Start-BitsTransfer -Source "https://futhark-lang.org/releases/futhark-nightly-windows-x86_64.zip" -Destination "futhark-nightly-windows-x86_64.zip"
          Expand-Archive futhark-nightly-windows-x86_64.zip
          Write-Output "::add-path::$(Get-Location)/futhark-nightly-windows-x86_64"
      - name: Setup Zig
        uses: goto-bus-stop/setup-zig@v1.2.3
        with:
          version: master
      - name: Build Calculo
        run: zig build
      - name: Archive artifacts
        uses: actions/upload-artifact@v2
        with:
          name: calculo
          path: |
            zig-cache/bin/calculo.exe
