name: Main

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2.3.2
      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y haskell-stack ocl-icd-opencl-dev
      - uses: actions/cache@v2
        name: Cache ~/.stack and .stack-work
        with:
          path: |
            ~/.stack
            .stack-work
          key: ${{ runner.os }}-stack
      - name: Clone Futhark
        run: git clone https://github.com/diku-dk/futhark.git
      - name: Build Futhark
        run: |
          cd futhark
          stack setup
          stack build
          stack install
      - name: Setup Zig
        uses: goto-bus-stop/setup-zig@v1.2.3
        with:
          version: master
      - name: Build Calculo
        run: zig build
  build-mac:
    runs-on: macos-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2.3.2
      - name: Install Dependencies
        run: |
          brew install haskell-stack
      - uses: actions/cache@v2
        name: Cache ~/.stack and .stack-work
        with:
          path: |
            ~/.stack
            .stack-work
          key: ${{ runner.os }}-stack
      - name: Clone Futhark
        run: git clone https://github.com/diku-dk/futhark.git
      - name: Build Futhark
        run: |
          cd futhark
          stack setup
          stack build
          stack install
      - name: Setup Zig
        uses: goto-bus-stop/setup-zig@v1.2.3
        with:
          version: master
      - name: Build Calculo
        run: zig build
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2.3.2
      - name: Install Dependencies
        run: |
          choco install -y haskell-stack
      - uses: actions/cache@v2
        name: Cache ~/.stack and .stack-work
        with:
          path: |
            ~/AppData/Roaming/stack
            .stack-work
          key: ${{ runner.os }}-stack
      - name: Clone Futhark
        run: git clone https://github.com/diku-dk/futhark.git
      - name: Build Futhark
        shell: bash
        run: |
          cd futhark
          stack setup
          stack build
          stack install
      - name: Setup Zig
        uses: goto-bus-stop/setup-zig@v1.2.3
        with:
          version: master
      - name: Build Calculo
        run: zig build
